version: "3.4"

services:
  drones-ingester:
    build: ./drones-ingester
    env_file:
       - 'env'
  drones-api:
    build: ./drones-api
    env_file:
      - 'env'
  #   environment:
  #     DRONES_API_URL: "http://drones:5000"      
    ports:
      - "8002:5000"
  # mongo:
  #   image: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mlalandag
  #     MONGO_INITDB_ROOT_PASSWORD: mlalandag
  #   volumes:
  #     - mongodb:/data/db/